# Generated by Django 4.0.3 on 2024-09-04 07:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pybo1', '0005_answer_voter_question_voter_alter_answer_author_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='question',
            old_name='auther',
            new_name='author',
        ),
    ]
